#!/usr/bin/env bash
sudo ufw status
sudo nano /etc/default/ufw - IPV6=yes
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw disable
sudo ufw enable
sudo ufw allow http
sudo ufw allow 443
sudo ufw status verbose
